#ifndef REGISTERS_MEMORY_H_
#define REGISTERS_MEMORY_H_

// referenced at 18-Jul-2022 https://wiibrew.org/wiki/Hardware/Memory_Controller
//                           https://wiibrew.org/wiki/Hardware/Memory_Interface

// memory interface
#define MEM_MARR0_START 0x00
#define MEM_MARR0_END 0x02
#define MEM_MARR1_START 0x04
#define MEM_MARR1_END 0x06
#define MEM_MARR2_START 0x08
#define MEM_MARR2_END 0x0a
#define MEM_MARR3_START 0x0c
#define MEM_MARR3_END 0x0e
#define MEM_MARR_CONTROL 0x10
#define MEM_CP_BW_DIAL 0x12
#define MEM_TC_BW_DIAL 0x14
#define MEM_PE_BW_DIAL 0x16
#define MEM_CPUR_BW_DIAL 0x18
#define MEM_CPUW_BW_DIAL 0x1a
#define MEM_INT_ENBL 0x1c
#define MEM_INT_STAT 0x1e
#define MEM_INT_CLR 0x20
#define MEM_INT_ADDRL 0x22
#define MEM_INT_ADDRH 0x24
#define MEM_REFRESH 0x26
#define MEM_CONFIG 0x28
#define MEM_LATENCY 0x2a
#define MEM_RDTORD 0x2c
#define MEM_RDTOWR 0x2e
#define MEM_WRTORD 0x30
#define MEM_CP_REQCOUNTH 0x32
#define MEM_CP_REQCOUNTL 0x34
#define MEM_TC_REQCOUNTH 0x36
#define MEM_TC_REQCOUNTL 0x38
#define MEM_CPUR_REQCOUNTH 0x3a
#define MEM_CPUR_REQCOUNTL 0x3c
#define MEM_CPUW_REQCOUNTH 0x3e
#define MEM_CPUW_REQCOUNTL 0x40
#define MEM_DSP_REQCOUNTH 0x42
#define MEM_DSP_REQCOUNTL 0x44
#define MEM_IO_REQCOUNTH 0x46
#define MEM_IO_REQCOUNTL 0x48
#define MEM_VI_REQCOUNTH 0x4a
#define MEM_VI_REQCOUNTL 0x4c
#define MEM_PE_REQCOUNTH 0x4e
#define MEM_PE_REQCOUNTL 0x50
#define MEM_RF_REQCOUNTH 0x52
#define MEM_RF_REQCOUNTL 0x54
#define MEM_FI_REQCOUNTH 0x56
#define MEM_FI_REQCOUNTL 0x58
#define MEM_DRV_STRENGTH 0x5a
#define MEM_REFRSH_THHD 0x5c
#define MEM_CPUAHMR_REQCOUNTH 0x60
#define MEM_CPUAHMR_REQCOUNTL 0x62
#define MEM_CPUAHMW_REQCOUNTH 0x64
#define MEM_CPUAHMW_REQCOUNTL 0x66
#define MEM_DMAAHMR_REQCOUNTH 0x68
#define MEM_DMAAHMR_REQCOUNTL 0x6a
#define MEM_DMAAHMW_REQCOUNTH 0x6c
#define MEM_DMAAHMW_REQCOUNTL 0x6e
#define MEM_ACC_REQCOUNTH 0x70
#define MEM_ACC_REQCOUNTL 0x72
#define MEM_DDRREG_ADDR 0x74
#define MEM_DDRREG_DATA 0x76
#define MEM_DRV_PSTRENGTH 0x78

// memory controller
#define MEM_COMPAT 0x00
#define MEM_PROT_REG 0x02
#define MEM_PROT_SPL 0x04
#define MEM_PROT_SPL_BASE 0x06
#define MEM_PROT_SPL_END 0x08
#define MEM_PROT_DDR 0x0a
#define MEM_PROT_DDR_BASE 0x0c
#define MEM_PROT_DDR_END 0x0e
#define MEM_COLSEL 0x10
#define MEM_ROWSEL 0x12
#define MEM_BANKSEL 0x14
#define MEM_RANKSEL 0x16
#define MEM_COLMSK 0x18
#define MEM_ROWMSK 0x1a
#define MEM_BANKMSK 0x1c
#define MEM_PROT_SPL_ERR 0x1e
#define MEM_PROT_DDR_ERR 0x20
#define MEM_PROT_SPL_MSK 0x22
#define MEM_PROT_DDR_MSK 0x24
#define MEM_RFSH 0x26
#define MEM_AHMFLUSH 0x28
#define MEM_AHMFLUSH_ACK 0x2a
#define MEM_SEQRD_HWM 0x68
#define MEM_SEQWR_HWM 0x6a
#define MEM_SEQCMD_HWM 0x6c
#define MEM_CPUAHM_WR_T 0x6e
#define MEM_DMAAHM_WR_T 0x70
#define MEM_DMAAHM0_WR_T 0x72
#define MEM_DMAAHM1_WR_T 0x74
#define MEM_PI_WR_T 0x76
#define MEM_PE_WR_T 0x78
#define MEM_IO_WR_T 0x7a
#define MEM_DSP_WR_T 0x7c
#define MEM_ACC_WR_T 0x7e
#define MEM_ARB_MAXWR 0x80
#define MEM_ARB_MINRD 0x82
#define MEM_PROF_CPUAHM 0x84
#define MEM_PROF_CPUAHM0 0x86
#define MEM_PROF_DMAAHM 0x88
#define MEM_PROF_DMAAHM0 0x8a
#define MEM_PROF_DMAAHM1 0x8c
#define MEM_PROF_PI 0x8e
#define MEM_PROF_VI 0x90
#define MEM_PROF_IO 0x92
#define MEM_PROF_DSP 0x94
#define MEM_PROF_TC 0x96
#define MEM_PROF_CP 0x98
#define MEM_PROF_ACC 0x9a
#define MEM_RDPR_CPUAHM 0x9c
#define MEM_RDPR_CPUAHM0 0x9e
#define MEM_RDPR_DMAAHM 0xa0
#define MEM_RDPR_DMAAHM0 0xa2
#define MEM_RDPR_DMAAHM1 0xa4
#define MEM_RDPR_PI 0xa6
#define MEM_RDPR_VI 0xa8
#define MEM_RDPR_IO 0xaa
#define MEM_RDPR_DSP 0xac
#define MEM_RDPR_TC 0xae
#define MEM_RDPR_CP 0xb0
#define MEM_RDPR_ACC 0xb2
#define MEM_ARB_MAXRD 0xb4
#define MEM_ARB_MISC 0xb6
#define MEM_ARAM_EMUL 0xb8
#define MEM_WRMUX 0xba
#define MEM_PERF 0xbc
#define MEM_PERF_READ 0xbe
#define MEM_ARB_EXADDR 0xc0
#define MEM_ARB_EXCMD 0xc2
#define MEM_SEQ_DATA 0xc4
#define MEM_SEQ_ADDR 0xc6
#define MEM_BIST_DATA 0xc8
#define MEM_BIST_ADDR 0xca

#endif // REGISTERS_MEMORY_H_